/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCart: typeof import('element-plus/es')['ElCart']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterStatement: typeof import('./src/components/FooterStatement.vue')['default']
    IconAll: typeof import('./src/components/icons/IconAll.vue')['default']
    IconConversion: typeof import('./src/components/icons/IconConversion.vue')['default']
    IconEmail: typeof import('./src/components/icons/IconEmail.vue')['default']
    IconFunny: typeof import('./src/components/icons/IconFunny.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconGiveUp: typeof import('./src/components/icons/IconGiveUp.vue')['default']
    IconHot: typeof import('./src/components/icons/IconHot.vue')['default']
    IconPhone: typeof import('./src/components/icons/IconPhone.vue')['default']
    IconQQ: typeof import('./src/components/icons/IconQQ.vue')['default']
    IconRecently: typeof import('./src/components/icons/IconRecently.vue')['default']
    IconTable: typeof import('./src/components/icons/IconTable.vue')['default']
    IconTriangle: typeof import('./src/components/icons/IconTriangle.vue')['default']
    IconWeixin: typeof import('./src/components/icons/IconWeixin.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewsCart: typeof import('./src/components/NewsCart.vue')['default']
    PersonalizedStatement: typeof import('./src/components/PersonalizedStatement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideHotCart: typeof import('./src/components/SideHotCart.vue')['default']
    SimpleBrowse: typeof import('./src/components/SimpleBrowse.vue')['default']
    TipBar: typeof import('./src/components/TipBar.vue')['default']
    UniversalHead: typeof import('./src/components/UniversalHead.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
